language: node_js
node_js:
    - "4.1"

notifications:
    email: false
    webhooks:
        urls:
        - http://lwefd.me/api/1/notify/travis
        on_success: always
        on_failure: always
        on_start: always

